# Generated by Django 5.2.12 on 2026-03-06 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0002_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="consumer",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "consumer"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="merchant",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "merchant"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merchant_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_record",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["consumer", "order_status"], name="orders_orde_consume_5e2d26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["merchant", "order_status"], name="orders_orde_merchan_5fb9c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["listing", "order_status"], name="orders_orde_listing_c20e57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_price__gt", 0)), name="order_total_price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="order_quantity_positive"
            ),
        ),
    ]
