# Generated by Django 5.2.12 on 2026-05-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("collected", "Collected"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
