# Generated by Django 5.2.12 on 2026-03-06 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("requested", "Requested"),
                            ("assigned", "Assigned to Charity"),
                            ("collected", "Collected"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                ("collection_start", models.DateTimeField()),
                ("collection_end", models.DateTimeField()),
                ("qr_hash", models.CharField(blank=True, max_length=255)),
                ("qr_expires_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "donation",
                "verbose_name_plural": "donations",
            },
        ),
        migrations.CreateModel(
            name="DonationRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message from charity to merchant explaining their need",
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "donation request",
                "verbose_name_plural": "donation requests",
            },
        ),
        migrations.CreateModel(
            name="ImpactReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("families_helped", models.PositiveIntegerField(default=0)),
                ("meals_provided", models.PositiveIntegerField(default=0)),
                ("weight_kg", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("notes", models.TextField(blank=True)),
                (
                    "photo_proof_urls",
                    models.JSONField(default=list, help_text="List of proof photo URLs"),
                ),
            ],
            options={
                "verbose_name": "impact report",
                "verbose_name_plural": "impact reports",
            },
        ),
    ]
