# Generated by Django 5.2.12 on 2026-03-06 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donations", "0001_initial"),
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="assigned_charity",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "charity"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donation",
                to="listings.listing",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="merchant",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "merchant"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donations_offered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="donationrequest",
            name="charity",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "charity"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donation_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="donationrequest",
            name="donation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="donations.donation",
            ),
        ),
        migrations.AddField(
            model_name="impactreport",
            name="charity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="impact_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="impactreport",
            name="donation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="impact_report",
                to="donations.donation",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["merchant", "status"], name="donations_d_merchan_117c92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["status", "collection_end"], name="donations_d_status_26de1f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="donationrequest",
            constraint=models.UniqueConstraint(
                fields=("donation", "charity"), name="unique_donation_charity_request"
            ),
        ),
    ]
