# Generated by Django 5.2.12 on 2026-06-13 14:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0004_listing_trending_score_listing_view_count"),
        ("orders", "0003_alter_order_order_status"),
        ("users", "0006_profileupdaterequest_profileupdatedocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Display name, e.g. 'Standard'", max_length=100),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique code used in business logic, e.g. 'standard'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "monthly_price_dzd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly price in Algerian Dinars",
                        max_digits=10,
                    ),
                ),
                (
                    "max_active_listings",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum simultaneous active listings. NULL = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "can_receive_donations",
                    models.BooleanField(
                        default=False,
                        help_text="Whether merchants on this plan can post donation listings.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether new subscriptions to this plan are allowed.",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription plan",
                "verbose_name_plural": "subscription plans",
                "ordering": ["monthly_price_dzd"],
            },
        ),
        migrations.CreateModel(
            name="CommissionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission rate as a percentage, e.g. 10.00 = 10%",
                        max_digits=5,
                    ),
                ),
                (
                    "applies_from",
                    models.DateField(
                        help_text="Orders completed on or after this date use this rate."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "commission config",
                "verbose_name_plural": "commission configs",
                "ordering": ["-applies_from"],
            },
        ),
        migrations.CreateModel(
            name="CommissionSettlement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "total_amount_dzd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("settled_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="users.merchant",
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_settlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "commission settlement",
                "verbose_name_plural": "commission settlements",
                "ordering": ["-settled_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("trial_started_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="Reserved for gateway integration. No-op until payment gateway exists.",
                    ),
                ),
                (
                    "merchant",
                    models.OneToOneField(
                        help_text="The merchant profile this subscription belongs to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription",
                        to="users.merchant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "merchant subscription",
                "verbose_name_plural": "merchant subscriptions",
            },
        ),
        migrations.CreateModel(
            name="SponsoredSlot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of sponsored listing slots purchased."
                    ),
                ),
                (
                    "price_per_slot_dzd",
                    models.DecimalField(
                        decimal_places=2,
                        default=2000,
                        help_text="Price per slot in DZD.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_amount_dzd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Computed: quantity × price_per_slot. Set on save.",
                        max_digits=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sponsored_slots",
                        to="users.merchant",
                    ),
                ),
            ],
            options={
                "verbose_name": "sponsored slot",
                "verbose_name_plural": "sponsored slots",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="SponsoredListing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "position_priority",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Lower value = higher in feed. Admin can adjust manually.",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Should mirror slot.period_end converted to datetime."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsored_entries",
                        to="listings.listing",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsored_listings",
                        to="billing.sponsoredslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "sponsored listing",
                "verbose_name_plural": "sponsored listings",
                "ordering": ["position_priority", "-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount_dzd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("online", "Online"),
                            ("waived", "Waived"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Bank transfer reference, receipt number, etc.",
                        max_length=255,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_payments",
                        to="users.merchant",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who marked this payment as received.",
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.merchantsubscription",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Plan at time of payment (snapshot).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription payment",
                "verbose_name_plural": "subscription payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommissionLedger",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "order_amount_dzd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot of order.total_price at time of pickup.",
                        max_digits=10,
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission rate at time of order (snapshot). Not recalculated.",
                        max_digits=5,
                    ),
                ),
                (
                    "commission_amount_dzd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Computed: order_amount * rate / 100. Immutable after creation.",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("settled", "Settled"),
                            ("waived", "Waived"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "consumer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consumer_commissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        help_text="Preserved even if listing is deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_entries",
                        to="listings.listing",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        help_text="Kept even if merchant is deleted for financial history.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commission_ledger",
                        to="users.merchant",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="The completed order this commission is for.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commission_entry",
                        to="orders.order",
                    ),
                ),
                (
                    "settlement_batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reserved for future batch settlement feature.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entries",
                        to="billing.commissionsettlement",
                    ),
                ),
            ],
            options={
                "verbose_name": "commission ledger entry",
                "verbose_name_plural": "commission ledger entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["merchant", "status"], name="billing_com_merchan_6ff739_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="billing_com_status_fbbafe_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sponsoredslot",
            index=models.Index(
                fields=["merchant", "status"], name="billing_spo_merchan_e405d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoredlisting",
            index=models.Index(
                fields=["is_active", "expires_at"], name="billing_spo_is_acti_60ffe5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsoredlisting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("listing",),
                name="unique_active_sponsored_listing",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(
                fields=["merchant", "-created_at"], name="billing_sub_merchan_227c2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionpayment",
            index=models.Index(fields=["status"], name="billing_sub_status_153cdd_idx"),
        ),
    ]
