# Generated by Django 5.2.12 on 2026-06-13 14:25

from django.db import migrations
from datetime import date


def seed_plans_and_configs(apps, schema_editor):
    SubscriptionPlan = apps.get_model("billing", "SubscriptionPlan")
    CommissionConfig = apps.get_model("billing", "CommissionConfig")

    # Create or update Trial Plan
    SubscriptionPlan.objects.update_or_create(
        slug="trial",
        defaults={
            "name": "Trial Plan",
            "monthly_price_dzd": 0.00,
            "max_active_listings": 10,
            "can_receive_donations": False,
            "is_active": True,
        },
    )

    # Create or update Standard Plan
    SubscriptionPlan.objects.update_or_create(
        slug="standard",
        defaults={
            "name": "Standard Plan",
            "monthly_price_dzd": 2000.00,
            "max_active_listings": None,
            "can_receive_donations": True,
            "is_active": True,
        },
    )

    # Create default CommissionConfig if not exists
    if not CommissionConfig.objects.filter(is_active=True).exists():
        CommissionConfig.objects.create(
            rate_percent=10.00,
            applies_from=date(2026, 1, 1),
            is_active=True,
        )


def remove_seeded_plans_and_configs(apps, schema_editor):
    SubscriptionPlan = apps.get_model("billing", "SubscriptionPlan")
    CommissionConfig = apps.get_model("billing", "CommissionConfig")

    SubscriptionPlan.objects.filter(slug__in=["trial", "standard"]).delete()
    CommissionConfig.objects.filter(rate_percent=10.00, applies_from=date(2026, 1, 1)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_plans_and_configs, remove_seeded_plans_and_configs),
    ]

