DONATION_STATUS_AVAILABLE = "available"
DONATION_STATUS_REQUESTED = "requested"
DONATION_STATUS_ASSIGNED = "assigned"
DONATION_STATUS_COLLECTED = "collected"
DONATION_STATUS_EXPIRED = "expired"
DONATION_STATUS_CANCELLED = "cancelled"

DONATION_STATUS_CHOICES = [
    (DONATION_STATUS_AVAILABLE, "Available"),
    (DONATION_STATUS_REQUESTED, "Requested"),
    (DONATION_STATUS_ASSIGNED, "Assigned to Charity"),
    (DONATION_STATUS_COLLECTED, "Collected"),
    (DONATION_STATUS_EXPIRED, "Expired"),
    (DONATION_STATUS_CANCELLED, "Cancelled"),
]

REQUEST_STATUS_PENDING = "pending"
REQUEST_STATUS_APPROVED = "approved"
REQUEST_STATUS_REJECTED = "rejected"

REQUEST_STATUS_CHOICES = [
    (REQUEST_STATUS_PENDING, "Pending"),
    (REQUEST_STATUS_APPROVED, "Approved"),
    (REQUEST_STATUS_REJECTED, "Rejected"),
]

QR_VALIDITY_HOURS = 24
