NOTIFICATION_TYPE_ORDER_CREATED = "order_created"
NOTIFICATION_TYPE_ORDER_FULFILLED = "order_fulfilled"
NOTIFICATION_TYPE_ORDER_CANCELLED = "order_cancelled"
NOTIFICATION_TYPE_ORDER_REMINDER = "order_reminder"
NOTIFICATION_TYPE_DONATION_AVAILABLE = "donation_available"
NOTIFICATION_TYPE_DONATION_REQUESTED = "donation_requested"
NOTIFICATION_TYPE_DONATION_ASSIGNED = "donation_assigned"
NOTIFICATION_TYPE_DONATION_COLLECTED = "donation_collected"
NOTIFICATION_TYPE_ACCOUNT_VERIFIED = "account_verified"
NOTIFICATION_TYPE_ACCOUNT_SUSPENDED = "account_suspended"
NOTIFICATION_TYPE_LISTING_EXPIRING = "listing_expiring"
NOTIFICATION_TYPE_SYSTEM = "system"

NOTIFICATION_TYPE_CHOICES = [
    (NOTIFICATION_TYPE_ORDER_CREATED, "Order Created"),
    (NOTIFICATION_TYPE_ORDER_FULFILLED, "Order Fulfilled"),
    (NOTIFICATION_TYPE_ORDER_CANCELLED, "Order Cancelled"),
    (NOTIFICATION_TYPE_ORDER_REMINDER, "Order Pickup Reminder"),
    (NOTIFICATION_TYPE_DONATION_AVAILABLE, "Donation Available"),
    (NOTIFICATION_TYPE_DONATION_REQUESTED, "Donation Requested"),
    (NOTIFICATION_TYPE_DONATION_ASSIGNED, "Donation Assigned"),
    (NOTIFICATION_TYPE_DONATION_COLLECTED, "Donation Collected"),
    (NOTIFICATION_TYPE_ACCOUNT_VERIFIED, "Account Verified"),
    (NOTIFICATION_TYPE_ACCOUNT_SUSPENDED, "Account Suspended"),
    (NOTIFICATION_TYPE_LISTING_EXPIRING, "Listing Expiring Soon"),
    (NOTIFICATION_TYPE_SYSTEM, "System Notification"),
]

NOTIFICATION_CHANNEL_IN_APP = "in_app"
NOTIFICATION_CHANNEL_EMAIL = "email"
NOTIFICATION_CHANNEL_SMS = "sms"

NOTIFICATION_CHANNEL_CHOICES = [
    (NOTIFICATION_CHANNEL_IN_APP, "In-App"),
    (NOTIFICATION_CHANNEL_EMAIL, "Email"),
    (NOTIFICATION_CHANNEL_SMS, "SMS"),
]

NOTIFICATION_PRIORITY_HIGH = "high"
NOTIFICATION_PRIORITY_NORMAL = "normal"
NOTIFICATION_PRIORITY_LOW = "low"

NOTIFICATION_PRIORITY_CHOICES = [
    (NOTIFICATION_PRIORITY_HIGH, "High"),
    (NOTIFICATION_PRIORITY_NORMAL, "Normal"),
    (NOTIFICATION_PRIORITY_LOW, "Low"),
]

# Delete read notifications older than this many days
NOTIFICATION_RETENTION_DAYS = 90
