# Generated by Django 5.2.12 on 2026-05-05 02:39

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0003_seed_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=False)),
                ("weight_content", models.FloatField(default=0.3)),
                ("weight_collab", models.FloatField(default=0.25)),
                ("weight_geo", models.FloatField(default=0.2)),
                ("weight_urgency", models.FloatField(default=0.15)),
                ("weight_merchant", models.FloatField(default=0.1)),
                ("distance_decay", models.FloatField(default=0.3)),
                ("max_distance_km", models.FloatField(default=5.0)),
            ],
            options={
                "verbose_name": "recommendation config",
                "verbose_name_plural": "recommendation configs",
            },
        ),
        migrations.CreateModel(
            name="ListingFeatureVector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slots",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        help_text="11-dimensional feature vector for the listing",
                        size=11,
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_vector",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "listing feature vector",
                "verbose_name_plural": "listing feature vectors",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature_vector",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=list,
                        help_text="Computed 11-dimensional feature vector",
                        size=None,
                    ),
                ),
                (
                    "preferred_categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("avg_discount_interest", models.FloatField(default=0.0)),
                (
                    "activity_pattern",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=list,
                        help_text="24-slot list of interaction probability by hour",
                        size=24,
                    ),
                ),
                ("total_interactions", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user recommendation profile",
                "verbose_name_plural": "user recommendation profiles",
            },
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("reserve", "Reserve"),
                            ("pickup", "Pickup"),
                            ("no_show", "No Show"),
                            ("cancel", "Cancel"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(help_text="Interaction weight/score")),
                ("timestamp", models.DateTimeField(help_text="Exact time of interaction")),
                ("time_of_day", models.IntegerField(help_text="Hour of the day 0-23")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user interaction",
                "verbose_name_plural": "user interactions",
                "indexes": [
                    models.Index(
                        fields=["user", "listing", "timestamp"],
                        name="recommendat_user_id_b46ff9_idx",
                    ),
                    models.Index(fields=["type"], name="recommendat_type_07a9e1_idx"),
                ],
            },
        ),
    ]
