# Generated by Django 5.2.12 on 2026-05-26 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_trending_score_listing_view_count"),
        ("recommendations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteraction",
            name="session_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional session identifier for grouping interactions",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="user_lat",
            field=models.FloatField(
                blank=True, help_text="User latitude at time of interaction", null=True
            ),
        ),
        migrations.AddField(
            model_name="userinteraction",
            name="user_lon",
            field=models.FloatField(
                blank=True, help_text="User longitude at time of interaction", null=True
            ),
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("content", "Content-Based"),
                            ("collab", "Collaborative"),
                            ("geo", "Geospatial"),
                            ("trending", "Trending"),
                            ("hybrid", "Hybrid"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(help_text="Hybrid fusion score at time of recommendation"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Rank position shown to the user, 1-indexed"
                    ),
                ),
                (
                    "reason_text",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable reason string shown in the UI",
                        max_length=200,
                    ),
                ),
                ("was_clicked", models.BooleanField(db_index=True, default=False)),
                ("was_reserved", models.BooleanField(db_index=True, default=False)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recommendation log",
                "verbose_name_plural": "recommendation logs",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="recommendat_user_id_33d3be_idx"
                    ),
                    models.Index(
                        fields=["listing", "was_reserved"], name="recommendat_listing_32c18e_idx"
                    ),
                    models.Index(
                        fields=["source", "was_clicked"], name="recommendat_source_30158a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "listing", "created_at"),
                        name="unique_recommendation_log_per_batch",
                    )
                ],
            },
        ),
    ]
