# Generated by Django 5.2.12 on 2026-03-06 04:55

import apps.core.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="email address"),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Algerian phone number (+213XXXXXXXXX or 0XXXXXXXXX)",
                        max_length=20,
                        unique=True,
                        validators=[apps.core.validators.validate_algerian_phone],
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("consumer", "Consumer"),
                            ("merchant", "Merchant"),
                            ("charity", "Charity"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        help_text="Type of user account",
                        max_length=20,
                    ),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("fr", "Français"), ("ar", "عربية"), ("en", "English")],
                        default="fr",
                        max_length=5,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150, null=True, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.CreateModel(
            name="Charity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization_name", models.CharField(max_length=255)),
                ("organization_name_ar", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("wilaya", models.CharField(blank=True, max_length=100)),
                (
                    "service_area",
                    models.JSONField(
                        default=list, help_text="List of wilaya names this charity serves"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("total_donations_received", models.PositiveIntegerField(default=0)),
                ("total_meals_provided", models.PositiveIntegerField(default=0)),
                ("total_families_helped", models.PositiveIntegerField(default=0)),
                (
                    "food_received_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charity_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_charities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "charity",
                "verbose_name_plural": "charities",
            },
        ),
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eco_score",
                    models.SmallIntegerField(
                        default=50,
                        help_text="Consumer eco score (0–100). Rewards responsible consumption.",
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("completed_orders", models.PositiveIntegerField(default=0)),
                ("cancelled_orders", models.PositiveIntegerField(default=0)),
                ("no_show_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_food_saved_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total kilograms of food saved through this account",
                        max_digits=10,
                    ),
                ),
                (
                    "dietary_preferences",
                    models.JSONField(
                        default=dict,
                        help_text='Consumer dietary preferences, e.g. {"is_vegan": true, "is_halal": true}',
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "consumer",
                "verbose_name_plural": "consumers",
            },
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_name", models.CharField(max_length=255)),
                ("business_name_ar", models.CharField(blank=True, max_length=255)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("bakery", "Bakery"),
                            ("supermarket", "Supermarket"),
                            ("cafe", "Café"),
                            ("hotel", "Hotel"),
                            ("other", "Other"),
                        ],
                        default="restaurant",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("wilaya", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal latitude (e.g. 36.7372)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Decimal longitude (e.g. 3.0869)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="PostGIS point for geographic queries. Auto-populated from lat/lng.",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("logo_url", models.URLField(blank=True)),
                ("cover_image_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("registration_number", models.CharField(blank=True, max_length=100)),
                ("tax_id", models.CharField(blank=True, max_length=100)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average rating from 0.00 to 5.00",
                        max_digits=3,
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("trust_score", models.SmallIntegerField(default=50)),
                ("total_listings", models.PositiveIntegerField(default=0)),
                ("total_orders_fulfilled", models.PositiveIntegerField(default=0)),
                ("total_donations", models.PositiveIntegerField(default=0)),
                ("food_saved_kg", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_merchants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "merchant",
                "verbose_name_plural": "merchants",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_user_ty_4573bb_idx"),
        ),
        migrations.AddIndex(
            model_name="charity",
            index=models.Index(
                fields=["verification_status"], name="users_chari_verific_f0d779_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="charity",
            index=models.Index(fields=["wilaya"], name="users_chari_wilaya_2dbff8_idx"),
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(
                fields=["verification_status"], name="users_merch_verific_8affdf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(fields=["wilaya"], name="users_merch_wilaya_27bbed_idx"),
        ),
    ]
