# Generated by Django 5.2.12 on 2026-03-08 20:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[("Home", "Home"), ("Work", "Work"), ("Other", "Other")],
                        default="Home",
                        max_length=20,
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("wilaya", models.CharField(max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("notes", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user address",
                "verbose_name_plural": "user addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
