# Generated by Django 5.2.1 on 2026-03-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_seed_categories"),
        ("users", "0002_user_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="listings.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "consumer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "favorite listing",
                "verbose_name_plural": "favorite listings",
            },
        ),
        migrations.AddIndex(
            model_name="favoritelisting",
            index=models.Index(fields=["user", "-created_at"], name="users_favor_user_id_221150_idx"),
        ),
        migrations.AddIndex(
            model_name="favoritelisting",
            index=models.Index(fields=["listing"], name="users_favor_listing_86d124_idx"),
        ),
        migrations.AddConstraint(
            model_name="favoritelisting",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"),
                name="unique_favorite_listing_per_consumer",
            ),
        ),
    ]
