# Generated by Django 5.2.12 on 2026-04-24 18:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merchant_location_gist_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="merchant",
            name="trust_score",
        ),
        migrations.AddField(
            model_name="charity",
            name="eco_score",
            field=models.SmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="charity",
            name="eco_score_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="charity",
            name="eco_tier",
            field=models.CharField(default="developing", max_length=20),
        ),
        migrations.AddField(
            model_name="charity",
            name="last_active_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="charity",
            name="total_no_shows",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="consumer",
            name="eco_score_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="consumer",
            name="eco_tier",
            field=models.CharField(default="developing", max_length=20),
        ),
        migrations.AddField(
            model_name="consumer",
            name="last_active_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="merchant",
            name="eco_score",
            field=models.SmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="merchant",
            name="eco_score_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="merchant",
            name="eco_tier",
            field=models.CharField(default="developing", max_length=20),
        ),
        migrations.AddField(
            model_name="merchant",
            name="last_active_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="merchant",
            name="total_no_shows",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="EcoScoreEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("delta", models.IntegerField()),
                ("score_before", models.IntegerField()),
                ("score_after", models.IntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(default="system", max_length=50)),
                ("admin_note", models.TextField(blank=True, null=True)),
                ("is_overridden", models.BooleanField(default=False)),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overridden_eco_score_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eco_score_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "eco score event",
                "verbose_name_plural": "eco score events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="users_ecosc_user_id_90aabe_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("related_object_id__isnull", False)),
                        fields=("user", "event_type", "related_object_id"),
                        name="unique_event_per_object",
                    )
                ],
            },
        ),
    ]
