# Generated by Django 5.2.12 on 2026-03-06 04:55

import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_ar", models.CharField(blank=True, max_length=100)),
                ("name_fr", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("icon_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveSmallIntegerField(default=0, help_text="Display order")),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ListingPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("photo_url", models.URLField()),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "listing photo",
                "verbose_name_plural": "listing photos",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_ar", models.CharField(blank=True, max_length=255)),
                ("title_fr", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                ("description_fr", models.TextField(blank=True)),
                ("original_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discounted_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="DZD", max_length=3)),
                ("quantity_total", models.PositiveIntegerField()),
                ("quantity_available", models.PositiveIntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("portion", "Portion"),
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("piece", "Piece"),
                            ("box", "Box"),
                            ("bag", "Bag"),
                            ("tray", "Tray"),
                            ("litre", "Litre"),
                        ],
                        default="portion",
                        max_length=50,
                    ),
                ),
                (
                    "freshness_grade",
                    models.CharField(
                        choices=[
                            ("A", "Grade A – Excellent"),
                            ("B", "Grade B – Good"),
                            ("C", "Grade C – Acceptable"),
                            ("F", "Grade F – Near Expiry"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draft", "Draft"),
                            ("sold_out", "Sold Out"),
                            ("expired", "Expired"),
                            ("donated", "Donated"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("pickup_start", models.DateTimeField()),
                ("pickup_end", models.DateTimeField()),
                ("is_donation", models.BooleanField(db_index=True, default=False)),
                (
                    "allergens",
                    models.JSONField(
                        default=list, help_text="List of allergen strings, e.g. ['gluten', 'nuts']"
                    ),
                ),
                (
                    "dietary_flags",
                    models.JSONField(
                        default=dict, help_text='e.g. {"is_vegan": true, "is_halal": true}'
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="listings.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "listing",
                "verbose_name_plural": "listings",
            },
        ),
    ]
