# Generated by Django 5.2.12 on 2026-03-06 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="merchant",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "merchant"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingphoto",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="listings.listing",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["merchant", "status", "created_at"], name="listings_li_merchan_52bb95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "pickup_end"], name="listings_li_status_49e11c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["is_donation", "status"], name="listings_li_is_dona_d9b48f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category", "status"], name="listings_li_categor_fcaf14_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("discounted_price__lte", models.F("original_price"))),
                name="discounted_price_lte_original",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_available__gte", 0)),
                name="quantity_available_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("pickup_start__lt", models.F("pickup_end"))),
                name="pickup_start_before_end",
            ),
        ),
    ]
