# Generated by Django 5.2.12 on 2026-05-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_seed_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="trending_score",
            field=models.FloatField(
                db_index=True,
                default=0.0,
                help_text="Normalised 0–1 score updated every 30 minutes by Celery. Reflects interaction velocity over the past 24 hours.",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total views — incremented on listing detail requests"
            ),
        ),
    ]
