# Generated by Django 5.2.12 on 2026-03-06 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("completed_orders", models.PositiveIntegerField(default=0)),
                ("cancelled_orders", models.PositiveIntegerField(default=0)),
                ("no_show_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue_dzd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("food_saved_kg", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("new_listings", models.PositiveIntegerField(default=0)),
                ("total_donations", models.PositiveIntegerField(default=0)),
                ("active_merchants", models.PositiveIntegerField(default=0)),
                ("active_consumers", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "daily metrics",
                "verbose_name_plural": "daily metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. login, order_created, listing_created",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "user activity",
                "verbose_name_plural": "user activities",
            },
        ),
    ]
