# Generated by Django 5.2.12 on 2026-03-06 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(help_text="Overall rating 1–5"),
                ),
                (
                    "food_quality_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Food quality rating 1–5", null=True
                    ),
                ),
                (
                    "freshness_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Freshness rating 1–5", null=True
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("photo_urls", models.JSONField(default=list)),
                ("is_visible", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
            },
        ),
    ]
