# Generated by Django 5.2.12 on 2026-03-06 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_created", "Order Created"),
                            ("order_fulfilled", "Order Fulfilled"),
                            ("order_cancelled", "Order Cancelled"),
                            ("order_reminder", "Order Pickup Reminder"),
                            ("donation_available", "Donation Available"),
                            ("donation_requested", "Donation Requested"),
                            ("donation_assigned", "Donation Assigned"),
                            ("donation_collected", "Donation Collected"),
                            ("account_verified", "Account Verified"),
                            ("account_suspended", "Account Suspended"),
                            ("listing_expiring", "Listing Expiring Soon"),
                            ("system", "System Notification"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_ar", models.CharField(blank=True, max_length=255)),
                ("title_fr", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("body_ar", models.TextField(blank=True)),
                ("body_fr", models.TextField(blank=True)),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Extra context payload, e.g. order_id, listing_id"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("in_app", "In-App"), ("email", "Email"), ("sms", "SMS")],
                        default="in_app",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("high", "High"), ("normal", "Normal"), ("low", "Low")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("order_notifications", models.BooleanField(default=True)),
                ("donation_notifications", models.BooleanField(default=True)),
                ("marketing_notifications", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "notification preference",
            },
        ),
    ]
