# Generated by Django 5.2.12 on 2026-06-15 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("in_app", "In-App"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("push", "Push"),
                ],
                default="in_app",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Order Created"),
                    ("order_fulfilled", "Order Fulfilled"),
                    ("order_cancelled", "Order Cancelled"),
                    ("order_reminder", "Order Pickup Reminder"),
                    ("donation_available", "Donation Available"),
                    ("donation_requested", "Donation Requested"),
                    ("donation_assigned", "Donation Assigned"),
                    ("donation_collected", "Donation Collected"),
                    ("account_verified", "Account Verified"),
                    ("account_suspended", "Account Suspended"),
                    ("listing_expiring", "Listing Expiring Soon"),
                    ("system", "System Notification"),
                    ("billing_trial_expiring", "Trial Expiring Soon"),
                    ("billing_subscription_expired", "Subscription Expired"),
                    ("billing_subscription_suspended", "Subscription Suspended"),
                    ("billing_commission_created", "Commission Entry Created"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="FCMDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("registration_id", models.TextField(help_text="Firebase Cloud Messaging token")),
                (
                    "device_type",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS"), ("web", "Web")],
                        max_length=20,
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=255)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("app_version", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM device",
                "verbose_name_plural": "FCM devices",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="notificatio_user_id_6cf42c_idx"
                    ),
                    models.Index(
                        fields=["device_id", "is_active"], name="notificatio_device__87bc93_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "device_id"), name="unique_fcm_device_per_user_device"
                    )
                ],
            },
        ),
    ]
