# Generated by Django 5.2.12 on 2026-04-02 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0004_merchant_location_gist_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserContext",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="chat_context",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recent_intents",
                    models.JSONField(
                        default=list, help_text="Last 10 detected intents for this user"
                    ),
                ),
                (
                    "common_issues",
                    models.JSONField(default=dict, help_text="Counts of issue types encountered"),
                ),
                (
                    "sentiment_history",
                    models.JSONField(
                        default=list, help_text="Last 20 sentiment scores for trend analysis"
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="User preferences e.g. language, notification settings",
                    ),
                ),
                ("total_conversations", models.PositiveIntegerField(default=0)),
                ("last_interaction", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "user context",
                "verbose_name_plural": "user contexts",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        help_text="Role snapshot at conversation start (consumer/merchant/charity)",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                            ("human_handled", "Human Handled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("resolved", "Resolved"),
                            ("unresolved", "Unresolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="unresolved",
                        max_length=20,
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="User satisfaction rating 1-5", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="Categorization tags e.g. [payment_issue, high_priority]",
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of this conversation for admin context",
                    ),
                ),
                (
                    "last_sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Last detected sentiment score (-1 negative to +1 positive)",
                        null=True,
                    ),
                ),
                ("message_count", models.PositiveIntegerField(default=0)),
                (
                    "assigned_admin",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who took over this conversation",
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "conversation",
                "verbose_name_plural": "conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("bot", "Bot"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("card", "Card"),
                            ("quick_reply", "Quick Reply"),
                            ("system_message", "System Message"),
                            ("attachment", "Attachment"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("text_content", models.TextField(blank=True)),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        help_text="Rich content: cards, quick replies, buttons",
                        null=True,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True, help_text="Detected intent e.g. FIND_ORDER", max_length=100
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(blank=True, help_text="AI confidence score 0-1", null=True),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Sentiment score for this message (-1 to +1)",
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "sender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat message",
                "verbose_name_plural": "chat messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntentFeedback",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_message", models.TextField(help_text="Original user input text")),
                ("predicted_intent", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                (
                    "actual_intent",
                    models.CharField(
                        blank=True,
                        help_text="Correct intent as provided by admin (for retraining)",
                        max_length=100,
                    ),
                ),
                (
                    "feedback_source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("system", "System (Automatic)"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(help_text="Was the AI prediction correct?", null=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intent_feedbacks",
                        to="chat.conversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="chat.chatmessage",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "intent feedback",
                "verbose_name_plural": "intent feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["user", "status"], name="chat_conver_user_id_f98e31_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["status", "assigned_admin"], name="chat_conver_status_be7c4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["created_at"], name="chat_conver_created_656b50_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"], name="chat_chatme_convers_c2caf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="chat_chatme_sender_58dc8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intentfeedback",
            index=models.Index(
                fields=["is_correct", "reviewed_at"], name="chat_intent_is_corr_a1a259_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intentfeedback",
            index=models.Index(fields=["predicted_intent"], name="chat_intent_predict_45d9dd_idx"),
        ),
    ]
