# Generated by Django 5.2.12 on 2026-05-14 00:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_hybrid_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="chat_conver_mode_518dd1_idx",
            old_name="chat_conver_mode_admin_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="chat_conver_priorit_c70888_idx",
            old_name="chat_conver_priority_idx",
        ),
        migrations.AddField(
            model_name="adminassignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="ai_suggested_reply",
            field=models.TextField(blank=True, help_text="AI co-pilot suggested reply for admin"),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="unread_admin_count",
            field=models.PositiveIntegerField(
                default=0, help_text="User messages not yet seen by admin"
            ),
        ),
        migrations.AddIndex(
            model_name="adminassignment",
            index=models.Index(
                fields=["conversation", "created_at"], name="chat_admina_convers_aa392b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminassignment",
            index=models.Index(fields=["admin", "action"], name="chat_admina_admin_i_d9b8ee_idx"),
        ),
    ]
