# Generated by Django 5.2.12 on 2026-05-23 23:19

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_rename_chat_conver_mode_admin_idx_chat_conver_mode_518dd1_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic_id", models.CharField(max_length=80, unique=True)),
                ("content", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                ("relevant_for", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
